require 'rubygems'
require 'git'
require 'rake/clean'

CLEAN.include(['*.bak'])

task :default => [:help]

desc "Show help"
task :help do
	system('rake -T')
end

desc "Make a new post"
task :new do
  t = Time.now
  title = $*[1..-1]
  ptitle = []
  title.each{|i| ptitle << i.downcase}
  ptitle = ptitle.join('-')

  date = t.strftime("%Y-%m-%d-#{ptitle}.md")

  startstring=<<-EOF
---
layout: post
title: #{title.join(' ')}
---

#{Time.now.strftime("%B %d, %Y, %H:%M")}

# #{title.join(' ')} #

EOF

  File.open(date, 'w') {|f| f.write(startstring) }	
  puts "File created: #{date}"
  exit
end

desc "Commit and push"
task :update do
	puts "New files: "
	# Try the git gem for this bit <<<< 
	system "git ls-files -o --exclude-standard"
	puts ">> Continue? y/N :"
	input = STDIN.gets.chomp
	if input == "y"
		system "git add $(git ls-files -o --exclude-standard)"
		system "git commit -a"
		system "git push"
	end
end
